-
  name: Ubuntu bootstrap
  hosts: localhost
  become: yes

  tasks:
    - name: Update repositories cache
      apt:
        update_cache: yes

    - name: Install apt list of packages
      apt:
        name: "{{ packages }}"
      vars:
        packages:
        - ack-grep
        - silversearcher-ag # similar to ack but can be used in vim
        - ansible
        - apache2-utils # tools like htpassword etc
        - apt-transport-https # helpful to have
        - audacity
        - awscli
        - bash-completion
        - caffeine
        - cbm # colour bandwidth monitor
        - curl
        - cifs-utils
        - feh
        - fonts-powerline
        - fortune # fortune at the top of your terminal
        - git
        - git-crypt
        - git-cola # gui for slicing git commits
        - go-dep # go dependency manager
        - i3 # window manager
        - i3lock # lock for i3
        - iftop # the top of network usage
        - iperf3 # network performance tests
        - iotop
        - jq
        - lxappearance
        - make
        - mutt
        - netcat
        - nethogs
        - neofetch # Gives you a prompt for screenshot
        - neovim 
        - nmap
        - nodejs
        - openvpn
        - pavucontrol
        - playerctl
        - polybar
        - ranger
        - ruby-all-dev
        - rofi
        - shellcheck
        - smartmontools
        - snap
        - software-properties-common
        - speedtest-cli
        - steam-installer
        - ssh
        - tcpdump
        - telnet
        - terminator
        - tmux
        - tree # nice way to view dir structure
        - ubuntu-drivers-common
        - vim
        - vim-gnome
        - virtualbox
        - vlc
        - wavemon # network interface statistics
        - xclip # install to copy out of tmux
        - xinit # allows a user to manually start an xorg display server
        - yarn
        - zsh

    - name: Install snaps
      snap:
        name:
          - core
          - core18
          - discord
          - docker
          - electronplayer # netflix player
          - fast # speedtester
          - gotop # CPU, MEM, Net monitoring tool
          - intellij-idea-community
          - ncspot
          - postman
          - spotify
          - zoom-client

    - name: Install snaps with option --classic
      snap:
        name:
          - ab
          - code
          - go
          - helm
          - hub
          - kubectl
          - ruby
          - rubymine
          - slack
        classic: yes
    
    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes
