-
  name: Ubuntu bootstrap
  hosts: localhost
  become: yes

  tasks:
    - name: Update repositories cache
      apt:
        update_cache: yes

    - name: Install apt list of packages
      apt:
        name: "{{ packages }}"
      vars:
        packages:
        - ack-grep
        - ansible
        - apache2-utils # tools like htpassword etc
        - apt-transport-https # helpful to have
        - awscli
        - bash-completion
        - cbm # colour bandwidth monitor
        - curl
        - cifs-utils
        - feh
        - git
        - git-crypt
        - i3 # window manager
        - i3lock # lock for i3
        - iftop # the top of network usage
        - iperf3 # network performance tests
        - ipscan
        - iotop
        - jq
        - lxappearance
        - make
        - netcat
        - nethogs
        - neofetch # Gives you a prompt for screenshot
        - nmap
        - openvpn
        - pavucontrol
        - ranger
        - ruby-all-dev
        - shellcheck
        - smartmontools
        - snap
        - software-properties-common
        - speedtest-cli
        - steam-installer
        - ssh
        - tcpdump
        - telnet
        - terminator
        - tmux
        - vim
        - vim-gnome
        - vlc
        - wavemon # network interface statistics
        - xclip # install to copy out of tmux
        - xinit # allows a user to manually start an xorg display server

    - name: Install snaps
      snap:
        name:
          - docker
          - fast # speedtester
          - kops
          - spotify
          - terraform-snap

    - name: Install snaps with option --classic
      snap:
        name:
          - code
          - helm
          - hub
          - kubectl
          - ruby
          - rubymine
          - slack
        classic: yes
    
    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes
