-
  name: Ubuntu bootstrap
  hosts: localhost
  become: yes

  tasks:
    - name: Update repositories cache
      apt:
        update_cache: yes

    - name: Install a list of packages
      apt:
        name: "{{ packages }}"
      vars:
        packages:
        - ansible
        - apt-transport-https
        - awscli
        - cbm # colour bandwidth monitor
        - curl
        - cifs-utils
        - git
        - git-crypt
        - iftop # the top of network usage
        - iperf3 # network performance tests
        - ipscan
        - jq
        - make
        - netcat
        - nethogs
        - nmap
        - openvpn
        - shellcheck
        - snap
        - software-properties-common
        - speedtest-cli
        - steam-installer
        - ssh
        - tcpdump
        - telnet
        - terminator
        - vim
        - vlc
        - tmux

    - name: Install snaps
      snap:
        name:
          - docker
          - fast # speedtester
          - kops
          - spotify
          - terraform-snap

    - name: Install snaps with option --classic
      snap:
        name:
          - code
          - helm
          - kubectl
          - ruby
          - rubymine
          - slack
        classic: yes
    
    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes